export const origin: string[] = [
  'http://127.0.0.1:5173',
  'http://localhost:5173',
  'http://192.168.1.114:5173',
  'http://192.168.0.116:3000',
  'http://localhost:3000',
];

export const allowedImageTypes: string[] = [
  'image/jpeg',
  'application/octet-stream',
  'image/jpg',
  'image/JPG',
  'image/JPEG',
  'image/png',
  'image/webp',
  'image/gif',
];

export const allStrings = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];

export const allowed_file_types: string[] = [
  'image/jpeg',
  'application/octet-stream',
  'image/jpg',
  'image/JPG',
  'image/JPEG',
  'image/png',
  'image/webp',
  'application/postscript',
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'image/gif',
];
